server:
  port: 5502
  host: localhost

database:
  url: "mongodb+srv://mrartimas24:mrartimas24@catalog-service.wuarc.mongodb.net/catalog_service?retryWrites=true&w=majority"

jwks:
  url: "http://localhost:5500/.well-known/jwks.json"

s3:
  region: eu-north-1
  bucket: mernspase-project
  accesskey: AKIARSU7K7WCF5FXE2XP
  secretkey: 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

 
 

 

 